topic_modelling:
  umap:
    n_neighbors: 15
    n_components: 10 
  hdbscan:
    min_cluster_size: 150  # depending on nr of statements, higher = lower nr topics
  bertopic:
    temperature: 3.0   # higher = softer distribution across topics
  vectorizer:
    min_df: 2
    max_df: 0.5
  output:
    top_k: 5
  encoding:
    batch_size: 64

semantic_similarity:
  scoring:
    alpha: 0.7
    top_k: 3
  encoding:
    batch_size: 64
