topic_modelling:
  buffer_multiplier: 1.7

semantic_similarity:
  scoring:
    alpha: 0.7
    top_k: 3
  encoding:
    batch_size: 64

modes:
  sample:
    input_path: data/sample
    input_name: null
    output_path: null
  restricted:
    input_path: B:\raw
    input_name: Statements_Home_Issue2_random500.xlsx
    output_path: B:\derived
